# Generated by Django 4.1.7 on 2023-04-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_price_order_product_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='productPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
