# Generated by Django 4.1.7 on 2023-04-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartSession',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
